### ISSUE TITLE
アイコンの画像変更が出来ない

### ISSUE THREAD

**Issue by tottoko8686** [nodchip/QMAClone#1079]
アイコンの画像を変更しようとするとアップロード中にエラーが発生しましたと表示されてしまいます。早く画像が変更できるようにしていただけると嬉しいです。よろしくお願いします。

**Comment by nodchip** [comment]
ご報告ありがとうございます。のちほど調査させていただきます。

**Comment by nodchip** [comment]
問題を確認いたしました。サーバーの設定の見直し、JDKのバージョンの変更等を行いましたが、問題を解決することができませんでした。今しばらくお待ちいただければ幸いです。

**Comment by tottoko8686** [comment]
ご確認ありがとうございます。現在、画像を利用した問題がリンク切れで指摘されはじめています。元からリンク切れだったか今回の問題が原因なのかわかりませんが。お忙しいとは思いますが早期の解決を期待しております。よろしくお願いします。

**Comment by nodchip** [comment]
画像を利用した問題で画像が表示されない問題につきましても、手元で確認しております。現在原因を調査中です。今しばらくお待ちください。

**Comment by nodchip** [comment]
画像を利用した問題でリンク切れが起こる問題につきまして、暫定的な修正を加えました。アイコン画像が変更できない問題については、根本的な原因が不明で、回避策も不明です。ご不便をおかけいたしますが、よろしくお願いいたします。

**Comment by tottoko8686** [comment]
問題の画像が表示されない件へのご対応ありがとうございました。

**Comment by tottoko8686** [comment]
こんばんは。アイコンが変更できなくなったのと同時期に起きている不具合？なのでこちらにご報告しておきます。それは問題作成画面に類似の問題が表示されなくなったことです。今までは問題作成画面で問題を送信する前に同じような問題がないかそちらで確認できていたのですが現在は0件ヒットの表示のみです。ご確認よろしくお願いします。

**Comment by nodchip** [comment]
ご報告ありがとうございます。類似問題が表示されない問題は、アイコンとは別の問題のようです。別途issueを登録していただいてもよろしいでしょうか？

**Comment by tottoko8686** [comment]
#1086のご解決ありがとうございました。プログラムに関してはまったくの素人なので見当違いならすみませんがこちらのトラブルも #1086同様にアップロードしようとした画像が登録される前に意図せず削除されてしまうという症状が原因だという可能性はありますでしょうか。画像に関するトラブルだったのでほんの少しでも関連性があればと思い #1086はご報告させていただいたのですが結果、見事に解決していただけたのでアイコンももしかしたらと思いまして。

まぁ問題の作成時の画像はＵＲＬを貼る方式ですし、アイコンの画像のアップデートは画像の出所や登録の手法が違うので全く関係ないかもしれませんが・・。お時間のある時にご見解を述べていただければと思います。よろしくお願いします。

**Comment by nodchip** [comment]
再度ログを確認いたしましたが、アイコンファイルをストレージに書き込むことができないことが直接的な原因のようです。 #1086 とは原因が異なっており、現時点で対処方法は不明となっております。

**Comment by tottoko8686** [comment]
ストレージがなにか分からなかったので検索してみたところデータを保存しておく場所、補助記憶装置のことなのですね。
数年分の大量のアイコン画像データがストレージの容量の許容範囲を超えてしまったのでしょうかね＞＜

現時点で対処方法は不明とのことなのでそれは残念ですがエラーの原因が判明しただけでも良かったと思います。
ご回答、ログを確認など、ご対応していただきありがとうございました。

**Comment by tottoko8686** [comment]
いつもお世話になっております。管理人さんに質問とご報告です。
まず質問ですがこの#1079のご報告から最近までは前にご報告した通り、アイコンの画像を変更しようとするとアップロード中にエラーが発生しましたが、先程アイコンのアップロードを行ってみたところアイコンのアップロードに成功しました。と表示されました。最近、ガイドラインの変更以外でなにか設定に変化を加えられましたか？　

報告はアップロードは成功するようになったのですがアップロードした画像がちゃんと表示されず、#1086 の画像リンク切れの時の画像しか表示されませんし、一度アップロードした後に更新するとアイコンが選択されていません、ファイル名が指定されていませんと表示されます。また、今までアップロードしていた画像がちゃんと表示されていたのに久々にログインしたら画像リンク切れの時の画像になった人もいるようです。

最後にお願いですがお時間があればまた対処方法を考えてみてはいただけないでしょうか。一応、前回までとは違いアップロード自体はできるようになっているので何か解決への糸口がみつかるかもしれません。プレイヤーのアイコン画像が表示されるようになるとプレイヤー一覧で友達や知人がログインしているかがすぐにわかるので助かるのです。よろしくお願いします。

**Comment by tottoko8686** [comment]
今、自分のデータで確認したところ、アイコン画面で選択されていません、ファイル名が指定されていませんと表示されるのは元々？のようです。アイコンの画像はアップロードしていた画像がそのまま表示されています。

上に書いた今までアップロードしていた画像がちゃんと表示されていたのに久々にログインしたらちゃんと表示されなくなった人は単に画像を別のに変更したから表示されなくなったっぽいです。

**Comment by Fujisawa0111** [comment]
kishibe.dyndns.tv/qmaclone/icon/ を確認させていただきましたら、ファイル数が63,815あるようでした。
例えば、FAT32形式のフォーマットですと、1フォルダ65,535ファイルの制限があったと思いますが、そのような制限に引っかかってることはありませんでしょうか？
とはいえ、最近のなら実質無限のファイルが扱える気がしますが…

**Comment by nodchip** [comment]
@Fujisawa0111 さん
ファイルシステムには ext4 を使用しております。 i-node には十分な余裕があります。
```
nodchip@gekigan:~$ df -i .
Filesystem       Inodes  IUsed    IFree IUse% Mounted on
/dev/sda2      61022208 366795 60655413    1% /

```

**Comment by Fujisawa0111** [comment]
@nodchip さん
ですよねぇ…
言語で弾かれてたり…もないでしょうしねぇ
