### ISSUE TITLE
アイコン画像のアップロードができません。

### ISSUE THREAD

**Issue by yunapo** [nodchip/QMAClone#1081]
アイコン画像をアップロードしようとすると
アップロード中にエラーが発生しました。と表示されてアップロードする事ができません。
ファイルサイズや画像自体の大きさ・形式等いろいろとためしたのですが
同じメッセージ表示されてしまう為、何が原因がわかりません・・・

**Comment by yunapo** [comment]
18日前にも同じ症状の方がいらっしゃったのに重複すいませんでした。
拝見させていただいたところ、まだ解決してないという事なのでしょうか。

**Comment by nodchip** [comment]
現時点において、原因不明、対処方法不明となっております。ご不便をおかけいたしますが、よろしくお願いいたします。
本issueは #1079 の重複として閉じさせていただきます。
