### ISSUE TITLE
プレイ中に起きる不具合について

### ISSUE THREAD

**Issue by tottoko8686** [nodchip/QMAClone#1082]
おはようございます。最近プレイ中に起こっている不具合のご報告です。
1つ目は赤文字エラーが発生する（プレイヤー情報の取得の失敗や問題の読み込みの失敗など）。
2つ目は問題を解答（全体の場合は全員が解答）しても次問の出題に進まずに残り時間のタイマーのみが動く時がある、などです。

ちなみにですが最近は早朝のメンテナンス的なことはされていないのでしょうか？いままでは6時ぴったりにメンテ→プレイヤー履歴には名義がなんも表示されていない状態になっていたのですが今日を含め数日はプレイヤー履歴に名が残ったままです。
上の不具合と早朝のメンテナンス？の有無が関係あるかはわかりませんが気になったのでこちらもご報告しておきます。

**Comment by nodchip** [comment]
ご報告ありがとうございます。

> 1つ目は赤文字エラーが発生する（プレイヤー情報の取得の失敗や問題の読み込みの失敗など）。
> 2つ目は問題を解答（全体の場合は全員が解答）しても次問の出題に進まずに残り時間のタイマーのみが動く時がある、などです。
これらはいずれもサーバー側のネットワークが不調の場合に起こる問題だと思われます。テレワークの広がりにより、各プロバイダーの負荷が上がり、ネットワークが不調となっているのだと思います。コラ側では制御ができないため、修正は困難です。

> ちなみにですが最近は早朝のメンテナンス的なことはされていないのでしょうか？いままでは6時ぴったりにメンテ→プレイヤー履歴には名義がなんも表示されていない状態になっていたのですが今日を含め数日はプレイヤー履歴に名が残ったままです。
> 上の不具合と早朝のメンテナンス？の有無が関係あるかはわかりませんが気になったのでこちらもご報告しておきます。
こちらにつきましては、サーバー側の自動処理スクリプトの不具合であることが分かりました。現在は修正済みで、明日の6時の再起動は意図通り行われるものと思います。

**Comment by tottoko8686** [comment]
在宅などのインターネット利用が拡大している影響なのですね。わかりました。
それと先ほどいつもの時間に無事再起動が行われたようで安心しました。
ご確認、ご対応ありがとうございました。

**Comment by nodchip** [comment]
本件いったん閉じさせていただきたいと思います。また同様の不具合がある場合は、Reopenをお願いいたします。
