### ISSUE TITLE
早朝の再起動

### ISSUE THREAD

**Issue by tottoko8686** [nodchip/QMAClone#1083]
おはようございます。昨日のサーバー移行の影響か本日は再起動後行われていませんでした。
前回同様、自動処理スクリプトに不具合が起きているかもしれませんのでご確認よろしくお願いします。

**Comment by nodchip** [comment]
ご報告ありがとうございます。設定ミスにより、1週間に1度再起動するようになっていました。修正いたしました。

**Comment by tottoko8686** [comment]
今朝、確認しましたが本日は再起動後行われていませんでした。

**Comment by nodchip** [comment]
ご報告いただきありがとうございます。

> 質問なのですが閉じられたissueのReopenはどうすればよいのでしょうか？
恥ずかしながら私は、英語が苦手でこのサイトについても正直よくわかっていないので今回はクローズされているこちらに書き込みしましたがと閉じられているissueに書き込みをしても、ちゃんと管理人さんに通知的なものは届くのでしょうか？

issueのReopenは管理人が間のようです。通知は管理人には届いております。

タイムゾーンUTCに設定されていたのが原因のようです。修正いたしました。

**Comment by tottoko8686** [comment]
昨日もご確認、修正されたようですが本日もいつもの時間に再起動されませんでした。
設定時間が違うだけで別の時間に再起動が行われているのなら良いのですが・・。

**Comment by nodchip** [comment]
ご報告ありがとうございます。
設定自体はできていると思いますので、もうしばらく様子を見たいと思います。

**Comment by tottoko8686** [comment]
本日は5時59分からプレイしてみましたがやはり6時になっても赤文字表示での中断が発生せず、そのまま1プレイ終わりました。しばらく様子をみるとのことなのでとりあえずこれで報告をストップしておきます。ご確認、ご対応ありがとうございました。
