### ISSUE TITLE
QMAClone検定に暴言吐いた輩について(再掲)

### ISSUE THREAD

**Issue by asagiri1** [nodchip/QMAClone#1084]
こんにちは。#1078を書いた者です。#1078が掲載されたのを受けてQMACloneの5ちゃんねるでまたQMAClone検定シリーズの悪口を書き込む輩がいました。先日、QMAClone検定シリーズの最新作が発表され、再びアンチが湧く可能性があります。
こちらを見ているにも関わらず全く反省の色が見られない彼らには何らかの対処をすべきだと思います。彼らには注意喚起をし、何としてでも謝罪をさせるべきで、もし謝罪がなければ制裁を加えるべきだと思います。
そちらの方で対処できないのであればこちらの方で独自の注意喚起をすることも視野に入れているのですが、いかがでしょうか?
コロナでストレスが溜まっていて、それどころではないのかも知れませんが、この件について真剣に考えていただきたく、再掲に至りました。

**Comment by toripii** [comment]
ご報告ありがとうございます。
前回同様の回答とはなりますが、ご報告いただいた件は「5ちゃんねる」上での出来事であり、QMAClone側の管理すべき範囲で生じている問題ではありませんので、QMAClone側として何らかの対処をとることはできませんし、とるべきでもないと考えています。記載いただいている注意喚起、謝罪要請などの独自の対応をご自身で行うにあたりましても、5ちゃんねる(または「検定」を投稿したサイト)の運営側に依頼すべきかと思います。
<b>外部のトラブルを招き入れることにもつながりますので、記載いただいたような対応をQMAClone内で行うことは絶対におやめください。</b>そのような行為を行った場合は、荒らし行為とみなす場合がございます。

本件は閉じさせていただきます。
たいへん恐縮ではございますが、重ねてご了承ください。

**Comment by asagiri1** [comment]
了解しました。5ちゃんねるの方で何とか頑張ってみます。
