### ISSUE TITLE
サイトにアクセスできない

### ISSUE THREAD

**Issue by tottoko8686** [nodchip/QMAClone#1085]
おはようございます。いつもお世話になっております。
本日早朝からＱＭＡＣにアクセス出来ない状態になっております。
ちなみにこの状態になる直前まで私はログインしていたのですが突如画面下に赤文字が表示され、それ以降アクセスできない状態になっています。

それと以前報告させていただいた♯1083の件ですがおそらく現在も設定どおりに再起動されていないと思われますのでそちらも併せて確認していただければと思います。よろしくお願いします。

**Comment by nodchip** [comment]
ご報告ありがとうございます。サーバーを再起動し、QMACloneにアクセスできることを確認いたしました。

#1083 につきましては、正しい設定方法が分かりました。明日6:00の再起動を確認し、官僚とさせていただきたいと思います。

**Comment by tottoko8686** [comment]
6時の再起動を先ほど確認いたしましたのでご報告いたします。
この度は本当にありがとうございました。

**Comment by nodchip** [comment]
ご報告ありがとうございました。
