### ISSUE TITLE
画像を使用した問題の修正時の不具合？

### ISSUE THREAD

**Issue by tottoko8686** [nodchip/QMAClone#1086]
いつもお世話になっております。リンク切れの問題を修正するために新しい画像のＵＲＬを貼ってみたところ　
https://upload.wikimedia.org/wikipedia/commons/8/8e/Nails.jpg←の画像（釘の画像）は問題作成画面に表示されません（リンク切れの時の画像が出る）。
いっぽうでhttps://upload.wikimedia.org/wikipedia/commons/2/2d/W_outou4051.jpg←の画像（さくらんぼ）は問題作成画面に
ちゃんと表示されました。共にwikipediaから同じ方法でＵＬＲをコピーして貼ったのですが釘の方が表示されない原因はなんでしょうか。#1079の画像トラブルとの関連性はあるのでしょうか？ご回答よろしくお願いします。

**Comment by nodchip** [comment]
ご報告ありがとうございます。
問題番号を教えていただけますでしょうか？

**Comment by tottoko8686** [comment]
問題番号は41815です。ちなみに送信確認の時点で画像が反映されていなかったため、送信は行っておりません。
ちなみに先ほど別の画像でも試してみましたが送信画面の時点でリンク切れ時の画像が表示されました。

**Comment by nodchip** [comment]
症状を確認いたしました。
ゲームサーバーに画像がキャッシュされておらず、wikimediaからダウンロードしようとしたのですが、ダウンロードしたはずのファイルが存在せず、ログにも何も出力されていないという状況です。
明日の朝、ログ出力を追加し、再度確認したいと思います。

**Comment by tottoko8686** [comment]
こんばんは。昨日の朝にログ出力を追加し、再度確認していただけるとのことでしたがいかがでしたでしょうか？
もし、まだでしたらお時間があるときで結構ですのでよろしくお願いします。

**Comment by nodchip** [comment]
失念しておりました…。時間のある時に対応させていただきます。

**Comment by nodchip** [comment]
本日のアップデートで画像がリンク切れとなる問題を修正いたしました。原因は一時ファイルに画像をダウンロードした際、意図せず一時ファイルが削除されていたことでした。ご不便をおかけして申し訳ありませんでした。

**Comment by tottoko8686** [comment]
先ほど確認いたしました。ご対応していただきありがとうございました。
