### ISSUE TITLE
同一人物による同一タイトルの作問について

### ISSUE THREAD

**Issue by tottoko8686** [nodchip/QMAClone#1087]
最近『テイルズ』というゲームシリーズの問題が連日、同一人物の手によって作成されています。
この同一人物によるテイルズシリーズの問題は今年に入って今日までの9か月で57問作成され、そのうち、この1週間で16問作成されています。中にはマニアックな内容の問題も含まれており、実際にその内容で指摘も受けています
（問題番号340798）。
ちなみにテイルズシリーズは作品数や登場キャラ、技や関わった声優などが多く、問題を作ろうと思えばいくらでも作れるほどなので今後もどんどん作成される可能性が非常に高いので早めに報告させていただきました。
どの程度で同一作品、種類、所属等の問題をゲームバランスが崩れるほどの作問と判断されるのか基準があるとその基準まで問題を作れることになってしまうので具体的な数字は出さなくて結構ですが現段階の作問状況に対する見解を回答していただければと思います。まだ問題ないとか今後次第で注意が必要など、おおまかな感じでいいのでよろしくお願いします。

**Comment by toripii** [comment]
ご報告ありがとうございます。
現時点では、当該プレイヤーによるゲームバランスを崩すほどの作問がなされているわけではないと判断いたします。
ただし、今後同様の作問が多数繰り返される場合はガイドラインに抵触する可能性がございますので、状況に変化がありましたら再度ご報告いただけますでしょうか。
よろしくお願いいたします。

**Comment by tottoko8686** [comment]
同一人物による同一タイトル、種類、所属等の作問についての近況報告と質問です。
まず去年の9月にご報告した人物ですが現在も『テイルズ』シリーズ関連問題を作成しており本日、テイルズ問が計80問目に到達しました。最近の作問ペースを考えますと今年夏のくらいまでには計100問に到達するのでは？と思っています。

次にぽっしゅという作問者（問題変更履歴のプレイヤー名は未初期化です）ですが、アイドルグループ（ももクロ）や水曜どうでしょうに関する問題を大量（ももクロ300問以上、水どう100問近く）に作成していて、この２つのテーマの5割から8割はほとんどこの人物の問題が占めています。

流石に後者はガイドライン違反でしょうが前者についてどう思われますか？まだ許容範囲でしょうか。
お時間があるときにご回答いただければと思います。よろしくお願いします。

**Comment by toripii** [comment]
ご返答が遅れ申し訳ございません。

上記につきまして、前者・後者ともに許容範囲を逸脱しているものと判断いたします。
特に後者は逸脱の度合いが悪質であるため、当該プレイヤーを警告処分といたします。
（前者についてはチャットでの注意でいったん対応いたします。）

加えて、後者のプレイヤーについて、「ももいろクローバーZ」「水曜どうでしょう」以外にも類似の事例がある場合は再度ご報告いただけますと幸いです。
以上、よろしくお願いいたします。

**Comment by tottoko8686** [comment]
ご対応、ご返答ありがとうございます。

まず、同一作品、種類、所属等の問題作成とは違う話になりますが「ぽっしゅ」氏のユーザーコードの一つがバグトラの#840にある理由で記入されています。それを参考に「ぽっしゅ」氏の作成した問題の編集履歴を見ますと2015年くらいまでは#840に記載されている「JYr0hXgY」のアカウントで作問しています。ところが2016年に作問されている問題番号318002では掲示板にも書かれている「7s4Pg8D8」に変わっています。もうこの頃には複数アカウントでの作問は禁止されており、「7s4Pg8D8」のアカウントで作問された問題は禁止行為である複数アカウントでの作問にあたるとおもわれます。
そこで質問なのですが上記のように、2013年以降に名義は変更していないがユーザーコードが違うアカウントで作問をしている場合も複数名義で作問された問題と同様に指摘対象になるのでしょうか？

次に本題です。現在、ぽっしゅ名義の問題は2717問登録されており、芸能3と4の問題だけで1277問あります。以下はそれらを検索して大雑把に確認した結果です。「ももいろクローバーZ」と「水曜どうでしょう」のように規制対象にすべき対象はありませんでしたがそこそこ多かったのは芸能のクイズ番組関連（番組自体はバラバラ）の問題80問、AKBの問題の79問、でんぱ組（アイドル）65問でした。報告は以上です。

質問に対するご返答はまたお時間のある時にしていただけると幸いです。よろしくお願いします。

**Comment by tottoko8686** [comment]
上の続きですが禁止事項には他の問題作成者と同じ名義の使用禁止という項目があります。「JYr0hXgY」のぽっしゅと
「7s4Pg8D8」のぽっしゅが同一人物だった場合、禁止行為である複数アカウントでの作問にあたります。
一方でもし別人だった場合は「7s4Pg8D8」がぽっしゅの名前を使って作問をしていたことになり、
それは禁止行為の他の問題作成者と同じ名義での作問になります。

次にこのぽっしゅ以外にも同様のパターンで作問名義は固定しているが複数のアカウントで作問しているプレイヤーがいます。そのプレイヤーは同じ名義で現在までに計7787問作成しているのですが問題変更履歴のプレイヤー名が未初期化です　
かつ作成アカウントがばらけているので同一人物なのか断定できません。
また、この作問数ですので「同一作品、種類、所属等の問題をゲームバランスが崩れると管理人が判断する程度に大量に投稿する行為」にあたる項目がある可能性があります。

複数名義での問題作成とは違い、複数アカウントでの問題作成の場合は以前、作問時に使用していたアカウントの
ユーザーコードをなくしてしまったから仕方なくの可能性もありますがユーザーコードの失念はプレイヤーの側の過失で、
複数回におよぶ複数アカウントの問題作成は問題あるかと思いますので追加でご報告させていただきました。以上です。

**Comment by toripii** [comment]
引き続いてのご報告ありがとうございます。

「ぽっしゅ」氏については、これまで報告いただいた内容に加え、複数アカウントでの問題作成を行っていることを確認しました。
こちらもガイドライン違反として警告対象とし、掲示板に追記しました。
その他の事項については現時点では警告等の対象となるか判断が難しいため、追加で報告したい情報がありましたら再度書き込みください。

以上よろしくお願いいたします。

**Comment by tottoko8686** [comment]
迅速に対応していただき感謝いたします。前回書いた類似の作問者のことをもっと詳しく書いておきます。

作問者名義は「はんごう」氏。現在、7787問作成しております。問題履歴のプレイヤー名は　未初期化です　です。
まず「同一作品、種類、所属等の問題をゲームバランスが崩れると管理人が判断する程度に大量に投稿する行為」にあたるであろう項目も『ポケットモンスター』関連の問題が84問。

次に複数のアカウントである例を挙げると全て作問名義は「はんごう」で291458の問題変更履歴のD6TpAs0kとIhSh7jJw、296781のD6TpAs0kとNluDoQHsとFUvvJjL1、306054のhSh7jJwとey6pM2ToとFUvvJjL1、など3問調べただけで
複数のアカウントが確認できます。どれも複数アカウントでの作問禁止のルールがはじまった2013年9月1日以降の履歴です。
作問者名義が「はんごう」で問題ノートに自塗りと書かれている問題を調べればおそらく他のアカウントも見つかると思います。また、はんごう名義の作問及び自塗りは少なくとも2020年の年末まで行われていたため、長い期間にわたって作問していたことが分かります。

期間や数で言えば「ぽっしゅ」氏よりも複数アカウントで作った作問数は多いはずですのでこちらも複数アカウントを用いた作問者として警告対象にすべきかと思います。ご検討ください。

**Comment by toripii** [comment]
ご報告ありがとうございます。

「はんごう」氏の『ポケットモンスター』関連の問題について確認しました。
ただし、他作問者による問題数も非常に多いため、この事例は現時点ではゲームバランスが崩れるほどの作問数ではないと判断いたします。

また、複数アカウントによる作問については、こちらで事象が確認当該事由による指摘を可とします。
先の「ぽっしゅ」氏への警告による対応は別のガイドライン違反行為が既に報告されていたことによるものですが、「はんごう」氏については現状では複数アカウントによる作問を足掛かりにこれ以外のガイドラインに抵触する行為を行っていることが確認できないため、一旦チャットでの注意とし、指摘対応への反応を踏まえてさらなる対応を検討したいと思います。ただし、追加の報告内容によっては即時警告処分をもって対応することを検討しております。

ご意見等お待ちしております。
以上よろしくお願いいたします。

**Comment by tottoko8686** [comment]
ご確認ありがとうございます。

ポケモン関連の問題数が非常に多いことは承知しております。
まぁポケモンについては2000問中80問くらいなのでその判断でいいと思います。
また、はんごう氏による作問及び自塗り問から複数アカウントを用いていること自体は確認していただけたようですので
とりあえず情報はここまでにしておきます。また何かしらの情報や動きがありましたらご連絡したいと思います。

ここまでご対応していただきありがとうございました。

**Comment by tottoko8686** [comment]
ご無沙汰しております。同一人物による同一タイトルの作問と複数名義、アカウントでの問題作成についてご報告です。

まず765というプレイヤーについてです。765はかつてバグトラの#841にて色々報告されていた人物で#841では765名義で1万問以上作成しているやそれ以外の理由で色々報告されています。
しかし、765はその後の765-と名義を変えて問題作成を継続していたようです。また、問題作問者が765だったものの名義を765-に変更し、765名義問の作成問題数をごまかした可能性もあります。現在、検索すると765名義は9867件ヒットで、
765-は836件なので。765-名義の問題の問題編集履歴には765と表示されているので同一人物であることは一目瞭然です。

次にサイロクについてです。上に書いたその765-名義の300771の問題履歴にはサイロクの名前が表示されています。
300771の問題掲示板にはサイロクが指摘者に対しに反論しています。そこでその掲示板に書いてある103594は誰が作成した
問題なのかを見てみましょう。103594の作問者は765です。当事者でなければ普通こんな反応しません。
それに103594は300771も自分が指摘解除しているはずなのに「300771の指摘が解除されたのでこの問題も解除します」という文や300771の普通に考えてリュウのあの技を「豪波動拳」と言うプレイヤーはメディアはないでしょう。という変な文など#841に書かれている日本語が変な点も共通しています。
サイロクは修正した問題の名義を自分のものにしたり、指摘されている他者の差し替えという理由で問題を塗り、
自分名義の問題作成を多数行った人物なのでこれが765の別アカではないかという考えはおかしくないと思います。
問題作成数が多いので同一人物による同一タイトルの作問がされている可能性も高いかと。

ユーザー間トラブル調整担当のとりぴーさんはどう思われますでしょうか。
ご意見をお聞かせいただければと思います。よろしくお願いします。

**Comment by toripii** [comment]
ご報告ありがとうございます。
以下順番に回答いたします。

・「765」氏と「765-」氏については、作問に使用したアカウントが同一であることを確認しました。
上記の両アカウントでの直近の活動がないこと、および後述の理由により、現状で上記2名は活動を行っていないものと判断し、改めて処分対象とはいたしません。
しかし同一アカウントで複数名義による作問を行っているため、上記2名が作成した問題については全問この理由により指摘可能との認識です。

・「サイロク」氏についても情報提供ありがとうございます。
ただし、現状で調査でき限りでは「765」氏および「765-」氏とのアカウントまたはIPアドレスの一致を確認できませんでした。このため、「サイロク氏」に関して上記2名のプレイヤーとの関連は現時点で不明と判断します。
複数アカウント/複数名義による作問、またその他ガイドライン違反行為についてなど、追加情報があればそれを待って追って判断したいと思います。

以上、ご理解のほどよろしくお願いいたします。

**Comment by tottoko8686** [comment]
ご返答ありがとうございます。まずサイロクについてです。
アカウントまたIPアドレスはバラバラでも同一人物が作問、編集していた例は前にもありましたし、103594や300771の作問者、問題変更履歴、問題掲示板に関わっている者同士が無関係だとは思えません。まぁ現段階では仕方ありません。

次に「765」及び「765-」についてです。
同一アカウントで複数名義による作問が行われていたことの確認をしていただけたことやこの作問者の作成した問題に対するご意見をいただけたのでもう十分です。

改めましてご返答ありがとうございました。また報告すべき件があればご連絡いたしますのでよろしくお願いします。

**Comment by tottoko8686** [comment]
追記。「765」ですが大文字の「７６５」でも作成しておりますのでこちらも指摘可能と認識しておいてください。
問題番号78962の問題履歴でIPの一致も確認しています。７６５◆kdA4cpNP@5m9aBl3F　765◆W3DruHcI@5m9aBl3F

**Comment by tottoko8686** [comment]
今の自分の立場上、連絡するのもおこがましいですが昨日あった作問に関する問題行為がありましたのでご連絡いたします。
作問者　もっちー　作問数が1日の上限を超える6問＋名義が他の作者名義と重複している
（310587と342186は作成アカウントが別々だが名義が一緒）

本来であれば名義重複で1問指摘をすれば名義の変更、また作問数を次回から抑えてもらえる可能性がありますが、
自分の制限理由が指摘の濫用によるものである可能性があるため、指摘を自重しています。
同者の行動が続くようなことがあればとりぴーさんの方で指摘、注意していただきたいと思います。
よろしくお願いします。

**Comment by tottoko8686** [comment]
予想はしておりましたが本日も作問者　もっちーにより作問が行われております。作問数は今日もこの連絡時点で6問作成です。名義のもっちーのままです。

このまま作問が継続されれば禁止行為である他の問題作成者と同じ名義の使用で作成された問題が段々増えていくことになります。そうならないためにも早く他の問題作成者と同じ名義の使用、一日に6問以上（6問も含む）の作問は禁止行為に当たることを気づかせる必要がありますので、指摘、注意の方をよろしくお願いします。

**Comment by tottoko8686** [comment]
お願いしていました、名義被りの方への注意を含めた指摘ですが、とりぴーさんからの動きが無かったので私の方で
1問指摘しておきました。また、別の作問者のタイピング問題と四択問題で疑問符をつけるべきなのにつけていない問題がありましたのでこちらにも1問指摘しておきました。今回は両方、新規の作問者っぽいのでとりあえず1問づつの指摘にしています。

現在、QMACloneには34万以上の問題が登録されており、その中には禁止行為にあたる作問から文章表現や書式のルールが守られていない問題などさまざまな理由で指摘に値する問題が存在します。よくあるパターンは順番当てで問題文の書式には
（注意：「並べなさい」「並べ替えなさい」のような語尾は存在しません。）と書いてあるにもかかわらず語尾が並べ替えなさい。になっているとか他の形式で疑問符をつけるよう書いてあるのに？がついていないとか、脚注が必要なのに脚注がない、固有名詞に『』、「」がついていない、時間経過で事実が変わったなどです（～される予定→もうされている）。
総合の問題数が多いのでこの類の問題が指摘や修正されていない状態で出題されているのまだ仕方がないとは思います。
ただ、この手の問題は指摘がされていれば作問者が指摘に気づいて、それを修正し、不具合のない問題になる場合がありますし、
それらが古い問題で元の作問者が修正できない場合でも他者が修正すれば不具合は改善されます。

一方で禁止行為である複数名義やアカウントで作成されていたのにもかかわらず今まで指摘されていなかった問題が
今も多数出題される状況にあります。こちらの一部は名指しでバグトラや指摘などで注意や警告を受けていたにもかかわらず、
当人は名義を統一するなどの対応もみせず、そのままにされていた問題です。こちらの場合は出題されるべき問題ではないので、本来は多く指摘されるべきだと思います。

話がそれてしまいましたが、今後、名義被りの方の名義に変更が行われず、作成数も6問以上が続くようなら
今度は管理人さん及びとりぴーさんの方で対応をお願いします。よろしくお願いします。

**Comment by toripii** [comment]
> お願いしていました、名義被りの方への注意を含めた指摘ですが、とりぴーさんからの動きが無かったので私の方で
> 1問指摘しておきました。また、別の作問者のタイピング問題と四択問題で疑問符をつけるべきなのにつけていない問題がありましたのでこちらにも1問指摘しておきました。今回は両方、新規の作問者っぽいのでとりあえず1問づつの指摘にしています。

確認が遅れ申し訳ございません。ご対応ありがとうございます。


> 話がそれてしまいましたが、今後、名義被りの方の名義に変更が行われず、作成数も6問以上が続くようなら
> 今度は管理人さん及びとりぴーさんの方で対応をお願いします。よろしくお願いします。

承知しました。重大な違反状態が継続する場合は改めて報告をお願いいたします。


あわせて、対応手順についてこの場で改めて整理します。

名義の重複、同一アカウントでの複数名義による作問については、全問これらの理由により指摘可能です。
これらのうち、
・現在進行形で違反状態が継続されていないもの
・現在進行形で違反状態が継続されているが軽微なもの、または初回違反時
については、まずプレイヤーの皆さんのほうで指摘機能をご使用ください。
違反の程度が悪質な場合や、指摘に対する対応が見込めない場合にこちらで対応を検討します。

以上、ご理解のほどよろしくお願いいたします。

**Comment by tottoko8686** [comment]
ご回答ありがとうございます。
同一アカウントでの複数名義についてですが同一アカウントで複数名義で作問されている方の中には
かなり初期（複数名義がまだ問題ではなかった頃？）に作問されている方もいますし、名前の前半部分は共通しているが
後半部分だけ変えているとか、同じような名前で表記がちょっと違うけど明らかに同一人物みたいな人がいます。
一方で比較的最近かつ同一アカウントでの複数名義状態の人物で指摘は必要かもしれないがバグトラなどで管理人さん達に
報告するほどではない程度の人もいます。後者はともかく、前者も含め同一アカ複数名義は全て指摘可能で良いのですか？
お時間があるときにご返答いただければと思います。

ついでに名義被りの方について進展がありましたので一応報告を。
名義被りの方ですが指摘していた問題の名義は昨日ちゃんと変更されていました。
ただ、指摘していない別の問題は変更されていなかったので他の問題の名義変更もしていただけるよう別の問題に指摘しております。本当は名義が変更されていない問題全てに指摘してもよかったのですが最近、指摘されていた問題が複数あったので、
修正しようとしたら制限？で修正できなくなっていたということが起きていますので（掲示板や他の作問者の問題掲示板に状況が書かれています）1問だけにしてます。以上です。

**Comment by tottoko8686** [comment]
名義の重複、同一アカウントでの複数名義また、それらを含む禁止行為について書かせていただきます。
違反の程度が悪質な場合や、指摘に対する対応が見込めない場合にこちらで対応を検討します。とあるように
管理側が対応する場合、すぐに対応されることはなく、それらが確認されるまで対象者はなにもされません。

一方、機械的制限は理由が指摘の数がなんらかの基準に達した場合など、即発動するようですが全てが上記のような違反行為関連で指摘されているわけではないのです。それなのに修正可能な内容でも指摘された数や割合次第で、制限対象となってしまい作問どころか指摘の修正すら出来なくなっています。他の理由あったとしてもです。

違反行為の状態が継続されているが指摘、対応がされていないことでいまだに出題される状態にある問題もあるのに
ガイドラインのルールを守っていても指摘が絡んだだけで制限され、出題もされない状態にあることは異常なことだと思いますがいかがですか？上記に書いた新規の作問者も本来であれば禁止行為に抵触している為、全問指摘されるべきで、
それらが指摘されればおそらく機械的制限状態になり、名義修正も不可状態になると思います。
修正機会はあったのに改善されなかったのですから指摘され、それで制限がかかったとしてもそれは仕方ありませんね？
サイトの仕様ですし、他の制限状態の人また違反状態ではないが指摘されている人からすれば見逃されている時点で不公平なのですから。違反状態が継続されている（主に同一アカウント、人物の複数名義による作問）他の問題や文章表現や書式に問題ある問題なども気づいた際は適度に指摘します。

**Comment by toripii** [comment]
ご返信遅くなり申し訳ございません。

>修正機会はあったのに改善されなかったのですから指摘され、それで制限がかかったとしてもそれは仕方ありませんね？

はい、この認識で問題ございません。
よろしくお願いいたします。

**Comment by tottoko8686** [comment]
上記にガイドラインのルールを守っていても指摘が絡んだだけで制限され、作問や修正が出来なくなっている人がいることについても書いていたのですが言及はいただけないのですか？

上でも触れていますが現在、指摘によって作問制限されている人は複数いると思われます。
全てがガイドライン違反を繰り返すようなプレイヤーで同理由で複数指摘を受けて、制限がかかっているのであれば、
何も思いませんが指摘されている人の問題の大半はガイドライン違反以外で指摘されている人が大半で制限がかかっていなければ修正可能な些細なレベルです。自らの問題を指摘した場合や他者の問題を修正した際に指摘解除し忘れて送信し、
解除されていない指摘状態が修正者に引き継がれてしまった場合も指摘がカウントされて制限になっていると思われます。
これらのプレイヤーは制限の基準もわからない、違反行為を行ったわけでもないのに制限になり、作問どころか
修正の機会すらないのです。ちなみに管理人さんも一時期、複数指摘状態になっていたため、多分制限状態にあると思われます。現在、管理人さんは作問されていないようなので影響はないでしょうがもし私の推測通り制限になっていたらどう思われますか？不満を持たず、素直に制限を受け入れられますか？とりぴーさんから管理人さんに聞いてみてください。

次に昨日80202が他者によって他者の問題が解答の修正されています。内容は解答が間違っていたための修正のようです。
修正者側は善意で修正したと思いますが本来であれば指摘を経ず、他者が作問者に無断で問題に手に加えることは指摘制度の意味がなくなるので良いことではありません。しかし、指摘を経ずに修正すれば上記のような制限の問題も起きないので
平和的に？解決します。現在、指摘制度は問題解決のための手段のはずなのに前者のような制限にまで影響してしまうため、後者のような修正の仕方の方が良いという矛盾した状況でもあります。

指摘、指摘による作問制限についてのあり方についてご回答よろしくお願いします。

**Comment by toripii** [comment]
ご意見ありがとうございます。
管理人様とも会話をしておりますが、以下の結論となります。

まず大前提として、**指摘内容の軽重、また他者の問題の指摘解除を忘れた場合など含めた各種状況に関係なく、
各ユーザーが自身で手を加えた問題を管理せず、指摘を無視していること自体が、ガイドラインの以下の項目に抵触すると考えています。**
>作成した問題の不具合を指摘された場合は問題掲示板を読み、ガイドラインに従って速やかに対応してください。

したがって、**指摘を受けた事由の悪質度に関係なく、自身の問題に対して指摘を受ける、修正時の指摘解除を忘れる、などの事由で付与された指摘を確認・管理する責任がユーザー側にあり、それを放置する行為は各ユーザー側の不注意で、管理を怠った時点で作問権限を停止されても仕方のない状況にあると考えています。**
※後述の通り、以前からユーザー側の設定により自身が作成・修正した問題に指摘が入っているかどうかの確認・管理は簡単に行えます。
この点の認識に齟齬があるようでしたので、ご確認ください。
なお、**他ユーザーの問題を塗り替える形で修正した問題に対して、別のユーザーから新たな指摘が入っている場合も対応責任は指摘を受けたユーザー側にあることになります。** ご注意ください。

上記前提も踏まえ、以下の理由により一定数の指摘を受けたことによる制限の方針自体に変更はありません。恐縮ですがご了承ください。
・自身の作問時(と指摘時)に自動的に正解率統計タブに問題が登録される設定にできる以上、他者の問題の指摘修正を行った場合も含め、自身の指摘問題への対応をしないこと自体がガイドライン上好ましいものではない。そのような問題が一定数に達している時点で、違反の度合いに関わらず制限がかかっても仕方のない状況と考えている。
・過去に指摘による作問権限停止措置を解除したら違反行為をエスカレートさせたユーザーがいた（この点は前回返答時に伝えきれていませんでした。申し訳ございません。）
・個別の作問制限解除に関する管理側のコストが膨大になる。また、ご意見いただいたような制限解除を都度判断する運用では、何をもって解除するかの判断基準が不明瞭となり、より大きなトラブルにつながりかねない。

またご意見を踏まえ、管理人様より以下の点の修正対応をいただいております。
・**「設定」>「その他」にある「問題作成時に自動的に正解率統計に登録する」と「問題指摘時に自動的に正解率統計に登録する」の設定を、全ユーザー対象に強制的に「オン」に変更する**
・「設定」>「その他」にある「問題作成時に自動的に正解率統計に登録する」と「問題指摘時に自動的に正解率統計に登録する」の設定を、初期状態で「オン」に変更する（新規ユーザーを念頭に置いた措置）
・**問題作成画面において、指摘を解除せずに送信しようとした場合に、指摘を解除することを推奨するダイアログを表示する。**

以上、よろしくお願いいたします。

**Comment by tottoko8686** [comment]
おっしゃていることはもっともですが、指摘内容の軽重、内容は関係ない、指摘を受けたユーザーが全部悪い、
よって作問権限を停止されても仕方のないというのは厳しすぎではありませんか？
1、指摘内容について
まず作成した時点では問題がなかったが画像リンク切れが発生していて指摘された場合。
一時期、サイト側の問題で既存の画像問題の画像が一切表示されない問題がありましたね？その時にはこれらが原因で画像リンク切れ理由で指摘された問題もあると思われます。当時、多数画像問題を作成していた人物はこれが原因で複数指摘を受け、制限になってしまった可能性もあるのです。

次に作成されていた時点から事実が変化した問題の場合。こちらの場合は事実が変化した時点で問題を修正できれば良いとはいえ全てのユーザーが即、事実関係の変化に対応できるわけではありません。ましてや現在、コロナや自然災害など様々な理由でそれどころではない人もいるでしょう。指摘を無視していること自体が悪いとおっしゃっていますが無視や放置しているのではなくどうしても対応できず指摘が累積された場合はどうしようもありません。

次に指摘を受けたのではなく自ら自身の問題を指摘していたプレイヤーの場合。
『指摘マークがついた問題が一定数に達すると作問権限が停止される。』というのは今回問題提起が起きたから初めて
公表されたはずです。もし、このことが初めから公表されていれば自らの問題を指摘するようなことはせずにすぐさま修正、
別問に変更で対応していたはずです。

2、指摘による制限に対する扱い
そもそも指摘に対応できなかったから作問権限を停止されても仕方のないという考え自体いかがなものでしょうか。
指摘についてはプレイヤー側に問題はあるにしろ、複数の作問者が現問題を訴えていることがすでに大きなトラブルです。
作問内容によって（事実関係の変化など）いっぺんに指摘され、一気に制限状態になる一定数に達する場合もあるのです。
本人に指摘解除する気があっても先に修正する権利を先に失っていてはどうしようもありません。
それと指摘による作問権限停止措置を解除したら違反行為をエスカレートさせたユーザーがいたからといって
また同じことが繰り返されるとは限りません。管理することも大事ですが少しはプレイヤーを信じてくれてもよいのではないでしょうか。一方で制限されるべきプレイヤー、指摘されるべき問題が放置されていることも問題です。
指摘された側、制限された側からすればこちらの方はお咎め無しというのは納得いきません。

最後にコストやリスク上、個別の作問制限解除自体が厳しいのは仕方がないですがそれならばせめて時間経過での解除の
処置、設定の確認を検討していただけないでしょうか。一応、別の対応で時間経過での解除の可能性は示唆されていましたが
『指摘マークがついた問題が一定数に達すると作問権限が停止される。』で制限されていた場合、もし仮に時間経過で
制限される時期になっても指摘状況に変化がないままだったなら再び一定数にひっかかりループ的に制限がかかるはずです。
また1に書いたような理由で指摘対応が行えなかった場合、2に書いたようにいっぺんに指摘された、制限になった場合でも
無期限的に制限されるというのはいくらなんでも厳しすぎます。

ご返答よろしくお願いします。

**Comment by toripii** [comment]
ご意見ありがとうございます。
返答としては「ご意見いただいたものすべてについて、対応が難しいか、対応すべきではないと考えている」となります。今後ご意見いただいてもこの部分が大きく変わる見込みはありませんので、大変恐縮ですがご理解いただきますようお願いいたします。

下記に個別の内容への返答を記載します。

①
>当時、多数画像問題を作成していた人物はこれが原因で複数指摘を受け、制限になってしまった可能性もあるのです。
>指摘を無視していること自体が悪いとおっしゃっていますが無視や放置しているのではなくどうしても対応できず指摘が累積された場合はどうしようもありません。
>作問内容によって（事実関係の変化など）いっぺんに指摘され、一気に制限状態になる一定数に達する場合もあるのです。

上記の事態についてはこちらも認識しております。
個々の事情についてはお察ししますが、これらの事態があったとしても過去に作成した問題の管理責任が現在まで継続して作問者にあることに変わりはない認識で、画像のリンク切れや事実関係が変化した場合なども含めて対応していただく必要があると考えています。
裏を返せば、いっぺんに指摘されて対応が難しくなるようであれば、そのような数の問題を作成すべきではありません。

②
>『指摘マークがついた問題が一定数に達すると作問権限が停止される。』というのは今回問題提起が起きたから初めて
公表されたはずです。

上記の機能の存在につきましては、過去にすでに公表されている内容です。たとえばhttps://github.com/nodchip/QMAClone/issues/762 をご覧ください。
こちらについては少しお時間をいただきますが、後ほど作問ガイドラインにも記載予定です。

③
>指摘についてはプレイヤー側に問題はあるにしろ、複数の作問者が現問題を訴えていることがすでに大きなトラブルです。
たいへん恐縮ですが、「複数の作問者」がtottoko86さん以外にいらっしゃることを把握しておりません。具体的にどなたが訴えているか把握されていますでしょうか。
いずれにせよ、少なくとも現状ではトラブルといえるような人数からの要望はない認識です。

④
>一方で制限されるべきプレイヤー、指摘されるべき問題が放置されていることも問題です。
指摘された側、制限された側からすればこちらの方はお咎め無しというのは納得いきません。

こちらについては、前回の私の返答内の下記部分と同様の返答となります。
>個別の作問制限解除に関する管理側のコストが膨大になる。また、ご意見いただいたような制限解除を都度判断する運用では、何をもって解除するかの判断基準が不明瞭となり、より大きなトラブルにつながりかねない。

現行の制度設計ではこの部分を「指摘された問題数」という計測可能な基準で判断しています。指摘された問題数が一定数に達していることが「制限されるべき」プレーヤーに該当する条件である、という考えです。
この条件をtottoko8686さんがお考えのような条件に変えることは技術的に困難であるだけでなく、基準に個別の判断が介在する制限となることでかえって対応の不公平感を増す結果につながると考えております。したがって、現時点でこの条件の変更予定はありません。
そのうえで、どうしても個別で対応が必要と考えられる事象がございましたら、本github等にて個別に連絡・対応依頼をいただければと思っております。

⑤
>それと指摘による作問権限停止措置を解除したら違反行為をエスカレートさせたユーザーがいたからといって
また同じことが繰り返されるとは限りません。

過去の事例の内容から、作問権限停止措置の解除を行うと、過去事例と同じかそれ以上の違反行為を行うユーザーが現れる可能性が極めて高いと判断しております。

⑥
>最後にコストやリスク上、個別の作問制限解除自体が厳しいのは仕方がないですがそれならばせめて時間経過での解除の
処置、設定の確認を検討していただけないでしょうか。

たいへん恐縮ですが、時間経過による作問権限停止の一時的解除(+再停止)については、こちらでも検討した結果実装は難しいとの結論に至っています。理由としては
・この実装が高コストで、かつ、条件の調整が難しく、技術的に実装が困難である。
・一時的な停止解除であっても、⑤で記したようなユーザーが現れる可能性が許容できないレベルである

以上、恐縮ですがよろしくお願いいたします。

**Comment by tottoko8686** [comment]
③の作問制限についてですが掲示板の51117と52917や問題番号332472の問題掲示板に同症状であることが書かれていますし、
バグトラの1076や1093で助けを求められていますが私以外を把握していないというのはどういうことですか。
私しか訴えていないというのはバグトラの1076や1093、掲示板、問題掲示板の書き込みも私だというのですか？
さすがに心外です。

⑤を見る限りもう管理側的にはユーザーに対し一切妥協はないのですね。
昔は問題行為をエスカレートさせるような相手すら救っていたというのに。

**Comment by toripii** [comment]
ご返信遅くなり申し訳ございません。

>最後の確認に対してだけご返答いただければと思います。よろしくお願いします。

こちらについて回答いたします。
まず、
>指摘を受けた際にちゃんと修正していた人でもその数指摘されたらその時点でもうアウト。

こちらのご認識は誤っています。指摘数のカウントはある時点で指摘状態となっている問題の数を取得しており、指摘修正対応がなされている問題はカウント対象外となります。

>指摘側のミスであっても正当な指摘理由が書かれていない場合でも指摘された側が悪いのですね？

指摘側のミス、正当な指摘理由がない場合等でも、指摘状態であることがカウント基準となっており、そこに内容による対応の差異はございません。
指摘側のミス、正当な指摘理由がない場合であっても、指摘内容を確認して指摘解除する対応を行っていないため指摘状態が継続しているのであって、作問者側の管理責任を果たしていないことが問題と考えております。
上記の観点を含めた指摘内容の軽重、および指摘事由の悪質度については、管理側の調査・対応コストが大きいことのほか、対応に管理側の恣意性が入ってしまう恐れが大きいため、一切考慮は行いません。
以上ご理解いただけますと幸いです。

大変恐縮ですが、本件につきましては現時点でこれ以上の進展・再検討の見込みはありませんので、クローズさせていただきます。
要望等ございましたら別途チケットを作成してお寄せいただければと思います。よろしくお願いいたします。
