### ISSUE TITLE
作問に関する禁止行為、その行為に対する指摘について

### ISSUE THREAD

**Issue by tottoko8686** [nodchip/QMAClone#1089]
いつもお世話になっております。いくつか確認、ご報告があります。
①本日いいいい、という作問者が1人あたり同一日に6問以上の問題作成行っております。
これは1度目ではなく2度目です。一度目は9月9日に341544～341554範囲内のうちの9問を1日で作成し、2度目は本日10月15日にこの報告時点で、すでに341635～341643範囲内のうちの8問も作成し、再度違反行為を行っております。
本人は同一日に6問以上の問題作成と知っていながらまた6問以上作っているはずなので（341553で1人あたり同一日に6問以上の作問禁止で指摘を受け、その後解除している）。チャットか掲示板での注意、警告、が必要かもしれません。

②禁止行為である複数名義で作問された問題や今回のような一日に6問以上作成の7問目以降問題など指摘を受けても仕方がないような問題が指摘されずにそのまま出題されている問題が多数あります。要はルールを破って作問した問題でも指摘さえされなければ問題自体は出題されるという状態です。そこで確認なのですがこれらの問題に対しては禁止行為に該当する問題である確証があれば指摘しても問題ありませんよね？

③これは現在進行形ではありませんが他者が禁止行為である同一作問者による同一内容・形式違いの出題の指摘を受けた問題（問題番号40281など）や指摘された問題をちょびっと修正しただけで名義を自分の名義に変更してる（問題番号942など）問題が多数（軽く100問以上）ありました。これらの問題は本来放置すべき、また修正できる問題でも名義は元作問者の名義のままにすべきであり、他者の問題を自分の物に変更する行為は一種の乗っ取り行為だと思うのですがどうでしょうか？

①に関してはまだ軽微なので様子見でもかまいませんが②③は結構重大だと思います。ご回答よろしくお願いします。

**Comment by toripii** [comment]
ご報告ありがとうございます。

①チャットにて注意喚起を行いました。同様の行為が継続して行われる場合は改めてご連絡ください。

②ご認識の通り、指摘して問題ありません。

③ガイドラインに
　
　"問題の不具合を指摘後一ヶ月以上問題が更新されない場合は、誰でもその問題を修正することができます。"

と記載のある通り、指摘を放置した状態で一ヶ月以上経過した問題については作問権限のあるユーザーであれば自由に書き換えを実行できます。ご指摘の問題に関しては指摘事由を解消するような修正を加えたうえで別の作問者が指摘解除しており、ガイドライン上特に問題のない行為であると考えます。

以上、ご認識のほどよろしくお願いいたします。

**Comment by anonymousnn** [comment]
横から失礼致します。
③の名義変更行為について、ガイドラインに「問題を修正する際、題意を保ったまま修正できる場合は最低限の修正のみに留めてください。」とあり、
指摘内容の修正は問題無いとしても、問題作成者の勝手な変更については「最低限の修正」を越えていると思われます。
また、過去に#1015でも同様の行為を行った人物についての指摘があり、nodchip様よりガイドライン違反と判定されています。
（上記トピックの人物については他にも問題行為が多々ありましたが）

以上より、③の判定についてご再考頂ければ幸いです。

**Comment by tottoko8686** [comment]
まずは①②の件に関してのご回答、ご対応ありがとうございました。

ただ、③に関してですが例にあげた962や158530のように1文字修正しただけで名義を自分の名義に変更しているパターンや
指摘内容が問題内容の重複だったのに、自らの名義に変更しただけで指摘解除している50461の例もあります。
さらに問題文を作問者の名義を変更で作問者をサイロクで検索すると164問ヒット、問題文を問題を修正で作問者をサイロクで検索すると76問ヒットしました。塗って問題を別の問題に変更したのであれば問題はありませんが、合計200問近くこの行為で他者の作った問題の名義を自分の名義に変更しており、他者の問題を自分のものにしてしまえという意図が感じられます。
上の方のご意見にもあるようにちょっと修正しただけで名義を変更は「最低限の修正」の範囲を超えているかと思います。
もう一度、③の判定についてご検討よろしくお願いします。

**Comment by tottoko8686** [comment]
あともう1点情報の追加です。215947では他の作問者が「複数名義での問題作成の禁止」で指摘されている問題なのにこれも名義をサイロクにして復活させていました。この人物に限らず「複数名義での問題作成の禁止」で指摘されている問題の指摘解除は流石によろしくないのでご報告しておきます。

**Comment by toripii** [comment]
皆様、ご意見いただきありがとうございます。
問題内容自体に指摘事由がない場合において、指摘対象となった問題を別のプレイヤーがそのまま再利用する行為自体については、（複数名義による作問・同一作問者の形式違い等事由に関わらず）先に回答した通り現行のガイドライン上は問題行為とみなすことができません。（ご指摘いただいている#1015についても、当該プレイヤーはほかの事例によりガイドライン違反と認定されているものと考えております）
同様の要望が強い場合、ガイドラインの改定を含め対応を検討したいと思っております。皆様におかれましては、本件に関してのご意見を本チケットもしくは掲示板等にて記載いただけますと幸いです。

以上、よろしくお願いいたします。

**Comment by tottoko8686** [comment]
ご回答ありがとうございます。現時点でガイドライン違反にあたらないのであればルールを改定すべきだと思います。

指摘内容が複数名義による作問・同一作問者の同一内容の形式違いのような作問者自身に問題があるパターンではなく、
誤字、脱字やフラグ、ジャンルの違いなどの作問者のちょっとしたミスだったり、画像問題のリンクが切れたなどの問題が
指摘されていた場合や忙しくて一か月修正する時間がなかった場合、作問者名義を他の人に乗っ取られていたら元の作問者は不満だと思いますし、異議を唱えると思います。

次に他者の指摘されていた問題を修正した人は#1015の人物やサイロク氏以外にも当然たくさんいるわけですが、問題の修正や再利用した人物がその問題の作問者名義を変更できるのであれば、現在、他者の問題の指摘内容を修正した人は全員名義を変更する権利があるということになります。現状のルールでは自分も修正して指摘を解除したことがあるので同然権利があり、今から指摘状態から復帰させた問題を全て自分名義に変えることも可能です。容認されている以上は。。。

個人の意見としてはこんなものでしょうか。ご検討ください。よろしくお願いします。

**Comment by toripii** [comment]
1週間の間こちらへの反応が多くないため、チャットにて投稿を行いました。一旦これを受けての推移を見守りたいと思います。
よろしくお願いいたします。

**Comment by toripii** [comment]
遅くなりましてたいへん申し訳ございません。
新規の書き込み等があるか推移を注視しており、2週間が経過しましたが、進展がありませんでした。

現時点では本件は以下のような対応とし、反対意見など出現した場合は再度ガイドラインの修正などを検討する方針で考えております。

①　同一作問者による問題内容の重複(作問形式の差異のみ)について**名義を変更するのみ**で指摘修正完了とする行為については、禁止行為としてガイドラインに記載する。
　(問題内容の重複により指摘対象となっていることは修正前に当然把握しているべき事項であり、ゲームバランスの崩壊につながる可能性があることを認識しているうえでの名義修正のみでの対応は許容されるべきではないと考えております)

②　①以外で、以下に該当する場合は指摘対象とする。(**名義修正のみの場合も修正者の作問とみなす**ことがポイントです)
　・指摘事項を解消しない修正を加えたのみである場合
　・名義修正により、当該作問者による問題数が1万問を超える場合
　　(ガイドラインの「1人あたり1万問を超える問題作成の禁止」に明記して対応)
　・名義修正により、当該作問者による同一日の作問数が6問以上となる場合
　　(ガイドラインの「1人あたり1万問を超える問題作成の禁止」に明記して対応)
　・名義修正により、当該作問者の作問数が「同一作品、種類、所属等の問題を、ゲームバランスが崩れると判断できる程度」に該当する場合
　　(ガイドラインの「1人あたり同一日に6問以上の問題作成」に明記して対応)
　・そのほか、ガイドラインの別の禁止事項に抵触する場合

③　①、②のいずれにも該当しない名義変更事例は、その行為自体については特に問題なしとする

④　以上について、過去の修正事例にさかのぼって適用はしない。


また、現時点で本チケットに寄せられている個々人については、遡及的措置となるため今回は特に追及対象としない方針です。

上記について反対意見が少なければ、1週間後を目途に順次対応していきたいと思います。
さらなるご意見や疑問点の書き込み、事例の報告等ございましたら、遠慮なくお寄せください。

**Comment by tottoko8686** [comment]
ご回答、ご提案ありがとうございます。
まず①②の関係者サイロクについて少し。問題作成者　サイロクで問題を検索すると2118件ヒットします。
流石に全部の詳細を調べたわけではありませんが2118件のうち、ほぼ全部が他者が指摘を受けた問題の名義を変更。or問題の差し替え（別の問題で上書き）。サイロク名義の問題の変更履歴には主に2018～2019年に最終更新された記録が残っていることから2018～2019年の一定の期間に大量に差し替えや名義変更を行っていたようです。④と追及しない方針を承知したうえで一応、書いときます。下から本題についてです。

まず①の「同一作問者による問題内容の重複(作問形式の差異のみ)」に該当して指摘されている問題について、名義を変更するのみで指摘修正完了とする行為については、禁止行為としてガイドラインに記載する。についてです。
残念ながらもう「同一作問者による問題内容の重複(作問形式の差異のみ)」の指摘を受けた問題はほとんどサイロクが名義変更して、指摘も解除してます。手遅れ感はありますが①の提案に賛成です。

次に②についてです。②にある「指摘事項を解消しない修正を加えたのみである場合」には
複数名義や複数アカウントで作られた問題を名義を変更するのみで指摘修正完了とする行為は該当しますか？
現在、指摘されている問題の9割近くが複数名義や複数アカウントで作られた問題なので非常に重要です。
個人的に上書きや名義を統一するための名義変更は正当な理由なので当てはまらない、それ以外はアウトだと思っています。
また②の項目の3点は、サイロク（名義の変更や差し替えを常習的また大量にやっていたことは当時は知りませんでした）が名義変更を含む指摘修正を行っていた時には問題提起できなかったのことなのでぜひ指摘対象に入れるべきかと思います。

最後に、本来なら①も②もガイドラインに必要なかったであろう項目ですが（現時点で対象者は1人なので）せっかくご提案していただいたのぜひ実行していただければと思います。今日の時点でこの2週間で意見がなかったことからおそらく他者からの意見は望めないかと思いますがよろしくお願いします。

**Comment by tottoko8686** [comment]
上の書き込みの追記です。また少し調べたところ、「同一作問者による問題内容の重複(作問形式の差異のみ)」で指摘されている問題を名義以外はなにも変更していないのに正解数のリセットを行っている問題もありました（正解率のリセットは問題内容が変更され正解率が上がると予想される問題以外は禁止）。

それは置いといて一応確認ですがご提案のルールが追加された場合、
①「同一作問者による問題内容の重複」で指摘を受けた問題は名義変更禁止
②・指摘事項を解消しない修正を加えたのみである場合は指摘対象とする
　・名義変更された問題は修正者が作問した問題扱いになり、作問数制限の対象になる。
③問題番号942や番号158530など指摘内容を修正さえしていれば名義変更してもよい。
この3点が追加されるということで良いでしょうか？以上です。

**Comment by toripii** [comment]
ご返答が遅くなり申し訳ございません。

まず質問に関して
>②にある「指摘事項を解消しない修正を加えたのみである場合」には
複数名義や複数アカウントで作られた問題を名義を変更するのみで指摘修正完了とする行為は該当しますか？
>個人的に上書きや名義を統一するための名義変更は正当な理由なので当てはまらない、それ以外はアウトだと思っています。
私としても上記の認識をしております。
上記でいう「それ以外」の場合とはつまり別の名義を用いるということで、複数名義での作問状態が継続している時点で指摘事項が解消されていないためです。

>それは置いといて一応確認ですがご提案のルールが追加された場合、
①「同一作問者による問題内容の重複」で指摘を受けた問題は名義変更禁止
②・指摘事項を解消しない修正を加えたのみである場合は指摘対象とする
　・名義変更された問題は修正者が作問した問題扱いになり、作問数制限の対象になる。
③問題番号942や番号158530など指摘内容を修正さえしていれば名義変更してもよい。
この3点が追加されるということで良いでしょうか？以上です。
上記のとおりです。

特に異論等がないようですので、上記をガイドラインに追加する旨を管理人nodchip様に要請いたします。
実際に運用する上で不都合が生じた場合は再度報告または問題提起していただけますでしょうか。

なお、問題作成者「サイロク」氏に関しては、チャットにて別途注意喚起を行います。
以上、ご了解いただけますと幸いです。

**Comment by tottoko8686** [comment]
とりぴー様へ
ご回答、ご対応ありがとうございました。了解いたしました。
管理人様へ
手数をおかけします。お時間があるときで結構ですのでよろしくお願いします。

**Comment by toripii** [comment]
管理人様より上記のガイドライン変更を行った旨確認いたしました。
また、プレイヤー「サイロク」氏に対し、チャットにて注意喚起を行いました。

本件はいったん対応済みとして閉じさせていただきます。
再度問題となる事態が発生しましたら、改めてご報告いただけますと幸いです。
恐れいりますが、よろしくお願いいたします。
