### ISSUE TITLE
アイコンの画像を変更しても変更した画像が表示されない

### ISSUE THREAD

**Issue by tottoko8686** [nodchip/QMAClone#1090]
いつもお世話になっております。症状自体は#1079と違いますので一応、別件としてご報告と質問いたします。
現在、変更自体は出来るようでアップロードするとアップロード成功と表示され、ファイル選択の隣にもアップデートした画像のデータ名が表示されます。しかし、アップデートした画像がちゃんと表示されません。アップロード後に更新するとファイル選択の隣の表示もデータ名は消え、選択されていません表示に戻ります。

次に色々試した結果http://kishibe.dyndns.tv/qmaclone/icon/にアイコン画像が登録されていることがわかりましたので調べてみたところ、最初の画像アイコンデータ2011年のnoimage.jpgから最後の画像データ | cmsnogxd.jpg | 2020-04-26 05:23 | 2.6Kまで記録されていることがわかりました。あれだけの量が記録されているなら限界が来るのも当然だと納得するほどのデータ量でした・・・。

そこで質問ですが | cmsnogxd.jpg | 2020-04-26 05:23 | 2.6K以降にアップロードした画像はhttp://kishibe.dyndns.tv/qmaclone/icon/に画像データが登録されてないから画像も正しく表示されない。という私の考えはあっていますでしょうか。お時間があるときにご回答よろしくお願いします。

**Comment by tottoko8686** [comment]
追加の報告ですが、上のサイトに登録されている http://kishibe.dyndns.tv/qmaclone/icon/noimage.jpg の画像をコピーし、アイコンのファイル選択時に貼り付けてみましたが他の画像同様にちゃんと表示されませんでした。なので上の仮説は見当違いだったようで登録されている画像であってもとダメなようです。#1079でのご説明通り、これもアイコンファイルをストレージに書き込むことができないことが原因なのでしょうかね＞＜。以上です。

**Comment by nodchip** [comment]
@tottoko8686 さん
ご質問いただきありがとうございます。 QMAClone の内部的には、アップロードされた画像は一旦ストレージに保存し、保存したフォルダ (ディレクトリ) を http://kishibe.dyndns.tv/qmaclone/icon/ として公開するようになっております。現在起こっているバグは画像 (およびその他のファイル) が、ストレージに保存できない場合があるというものです。このためアイコンが正しく表示されておりません。

**Comment by tottoko8686** [comment]
#1079の他の方の質問への回答も拝見しましたが画像などがストレージに保存できない問題と現在のデータの容量や数などは全く関係ないのですね。わざわざご回答いただきありがとうございました。
