### ISSUE TITLE
問題の修正が反映されない

### ISSUE THREAD

**Issue by tottoko8686** [nodchip/QMAClone#1092]
いつもお世話になっております。本日、問題の指摘解除のため問題を送信したのですが反映されませんでした。
昨日までは問題なく反映されていたので驚いております。

まずは管理人さん、もしくはとりぴーさんで問題の送信が反映されるか試してみてもらえないでしょうか。
私自身がその状態にあるのかを確認したいので。よろしくお願いします。

**Comment by tottoko8686** [comment]
度々すいません。昔のバグトラの作問権限停止された事例の色々確認したところ、もしかしたらという例がありましたのでご報告いたします。まず#915に書かれているエラー２７さんのコメント
・「詳細をお伝えしますと、「設定」-「指摘問題」の中で、名前が「未初期化」だったり、重複している問題に対して、明示的に自分の名前の「エラー２７」に変更しているうちに追加で問題登録が出来なくなりました。
おそらく、指摘問題を多数修正する中で、私自身が問題指摘されている状態となり、アクセス禁止されたものと推測しています。」とあります。現時点で私が修正して指摘マークが緑になっている問題は42問あります（時間経過で緑マークは消えるので管理人さん、またとりぴーさんが確認するころには数が減るかもしれませんので目印を。Twitterに載っている287419から313303までのうちの42問） 

・次に#762には一定数(一定比率？)を超える指摘を受けた作問者は新規作問が禁止されるとあります。
私が修正した42問が#915にあるとおり私自身が指摘を受けて解除した扱いになり、一定数(一定比率？)を超える指摘を受けた扱いになるならばそれが理由で作問制限が停止された可能性があります。

ご確認とそれらが原因で作問権限停止状態になっているのなら作問権限停止を解除していただければと思います。
よろしくお願いします。プレイヤー名義とIPは問題番号313303の問題変更履歴に記載されています。

**Comment by toripii** [comment]
ご報告ありがとうございます。
問題投稿については私のほうでは問題なく行えることを確認しております。

お問い合わせいただいた作問権限の制限に関連する情報については、恐縮ですが以下をご理解ください。
・ブラックリストをはじめ何らかの制限がかかっているかどうかについて、個別のユーザーが対象になっているかどうかの問い合わせには対応しておらず、その条件についても公開予定はありません。
・また、ブラックリストをはじめ何らかの制限がかかっている場合に、個別に解除対応をすることは原則ありません。

恐れ入りますが、いましばらく状況の変化がないかどうかお待ちいただけますでしょうか。
よろしくお願いいたします。

**Comment by tottoko8686** [comment]
ご回答ありがとうございます。
まず上の書き込みの特定にプレイヤーに関わる情報は関する情報は削除しておきました。お了承ください。

少なくとも自分に作問の制限がかかっていることだけは間違いないようです。
他の作問者の問題で名義も元のままにはしていたとはいえ連日、上限を超えた数を送信していたからなのか、それとも
それらの名義がバラバラだったので複数名義で作成しているようにとられたのか、またまた、違う理由でこうなったかわかりません。ただ、私が修正した問題は間違いなく他の作問者の問題で、自らが作成した問題はありませんし、
自分の問題を作るときは1つの名義しか使用していなかったことだけはお伝えさせてください。

どうであれ自分に何かしら原因があったから制限がかかったことには違いないので解除されるまで待たせていただきます。
お手数かけました。

**Comment by tottoko8686** [comment]
1087にも書きましたが自分の制限理由が指摘の濫用によるものである可能性があるため
少し、自らの指摘及び指摘問題の修正について説明させてください。

私が最近指摘してきた問題は同一アカウントで複数名義による作問を行っていた「765」「765-」名義の問題、
あかずきん氏が複数名義及び複数アカウントでの問題作成していた、ルキぱい、ふともも、どすけべビッチ、ちちウサギ名義の問題、アカウントa2jVLbqLを用いて大量の名義でマニアックな問題を多数作問していたゲーム氏の別名義で作成していた問題がほとんどです。一部『』がついていない、脚注や疑問符がついていないなどの問題文の書式に関しての指摘をしていました。
最近修正していた問題は修正可能なその手の問題修正でした。以上です。

**Comment by tottoko8686** [comment]
制限に気づいてから約2週間ほど経過しましたがやはり変化はありません。意見を述べさせてください。

まず作問が制限される場合、管理人さん・とりぴーさんの判断で制限をかけられるか機械的に制限がかかるの
どちらかです。両者の判断で制限されたのであればまず制限されるなにかしらの原因が自身にあったからなのですが
私はいきなり制限されるほどの行為を行っていたつもりはありません。一日の送信の上限を超えていた日もありましたが、
頻繁ではなかったはずですし、それが理由ならまず注意や警告など段階を踏んだ対応をされていたはずです。
また、一部作問者達に対する指摘行為が理由かと思いましたが指摘理由も正当な理由のある指摘ですし、
別issueのご対応で特に言及もなかったので、それが理由ではないと思っています。

次にガイドラインの禁止事項には機械的に各種権限の停止を行う場合もあると書かれています。
バグトラに寄せられている意見を見る限り、制限理由は指摘されている問題が一定数あった影響か制限がかかっていたや、
他者の指摘問題を多数修正を修正しているうち、制限がかかったなどです。
指摘マークがついている問題が複数あった場合で本人に修正する意思はあったのに制限がかかっていた、
指摘状態の問題数が他者の手によりに減っても、当時の指摘数で制限されていため、制限されている場合もあるようです。
私の制限される前の状況は自らが指摘されていた問題は０でしたが他者の問題を修正したことにより、
正解率統計に指摘解除した問題が登録され、それらが自らが指摘されていた問題と認識され、制限された可能性があります。
個人としてはこれしか考えられないかと思うのですが。

個別に解除対応をすることは原則ありませんとのことですが、もし、管理人さん・とりぴーさんの判断で制限がかかったのでなく、機械に上記の理由等で制限されていた場合なら恩赦的なものも考えていただいてもよいのではと思います。
お考えを聞かせていただければと思います。よろしくお願いいたします。

**Comment by tottoko8686** [comment]
ご回答ありがとうございました。
個別対応に対する不公平感、管理コストも大きすぎることは承知しておりますので個別対応に関しては仕方がありません。
時間経過で解除される可能性があるのならばその言葉を信じて待つだけです。

ここまで対応していただきありがとうございました。

**Comment by tottoko8686** [comment]
確認したいこととご報告があるの申し訳ありませんがまた意見を書きます。
まず確認ですが、迷惑行為や禁止行為が理由で人為的に制限されている場合と機械的に制限されているであろう場合の
処遇は勿論違いますよね？

他者のことなのですが本日、問題番号332472の問題掲示板に修正・投稿が出来ないとの書き込みがされています。
書き込みによると332472を問題内容の事実関係が変わってしまったので修正しようとしたが修正できなかったのでとりあえず出題されないよう自ら指摘したとのこと。ちなみにこの方が作成した他の問題を確認したところ指摘マークがついている問題は4問。332472を指摘する前は3問しか指摘状態でなかったことになります。また、その3問の指摘内容を確認したところ、それらも同様の理由で自ら指摘して一時的に出題されないように指摘していたようです。まぁそれ以前になにかしらの問題があったのかもしれませんが、この状態で制限になったのなら不憫です。

また、以前も少し触れましたが指摘関連が理由で制限がかかった可能性がある方が他にもいらっしゃいます。数に多少差はあるでしょうが数問程度しか指摘を受けていないのに制限がかかっており、本人に指摘を修正する意思はあるのに修正できない（掲示板、問題掲示板に修正しようとしたがと出来ないと書かれています）ようです。

もし、人為的に制限された側と上記の理由などで機械的に制限された側が両者同一とみなされているのなら流石にそれはおかしいと思いますのでそこは確認したいのです。処遇の違いについて（違いがあるかだけでも結構ですので）のご回答よろしくお願いします。

**Comment by tottoko8686** [comment]
確認したいこととご報告があるの申し訳ありませんがまた意見を書きます。
まず確認ですが、迷惑行為や禁止行為が理由で人為的に制限されている場合と機械的に制限されているであろう場合の
処遇は勿論違いますよね？

他者のことなのですが本日、問題番号332472の問題掲示板に修正・投稿が出来ないとの書き込みがされています。
書き込みによると332472を問題内容の事実関係が変わってしまったので修正しようとしたが修正できなかったのでとりあえず出題されないよう自ら指摘したとのこと。ちなみにこの方が作成した他の問題を確認したところ指摘マークがついている問題は4問。332472を指摘する前は3問しか指摘状態でなかったことになります。また、その3問の指摘内容を確認したところ、それらも同様の理由で自ら指摘して一時的に出題されないように指摘していたようです。まぁそれ以前になにかしらの問題があったのかもしれませんが、この状態で制限になったのなら不憫です。

また、以前も少し触れましたが指摘関連が理由で制限がかかった可能性がある方が他にもいらっしゃいます。数に多少差はあるでしょうが数問程度しか指摘を受けていないのに制限がかかっており、本人に指摘を修正する意思はあるのに修正できない（掲示板、問題掲示板に修正しようとしたがと出来ないと書かれています）ようです。

もし、人為的に制限された側と上記の理由などで機械的に制限された側が両者同一とみなされているのなら流石にそれはおかしいと思いますのでそこは確認したいのです。処遇の違いについて（違いがあるかだけでも結構ですので）のご回答よろしくお願いします。

**Comment by toripii** [comment]
ご意見ありがとうございます。

>まず確認ですが、迷惑行為や禁止行為が理由で人為的に制限されている場合と機械的に制限されているであろう場合の
処遇は勿論違いますよね？

いいえ、基本的に処遇は同じとなります。
作問制限に関しては、正しくは以下の通りご認識いただければと思います。

・機械的、手動にかかわらず作問制限は一律の基準をもって適用されているものである
・上記の基準の詳細を公開する予定はない
・基本的に管理者側で手動で制限を個別に解除する対応をとる予定もない

これは過去に作問制限を手動で解除したユーザーが違反行為を繰り返し、再度作問制限をかけざるを得ない事例が発生したためです。したがいまして、機械的に作問制限がかかっている場合と手動で作問制限がかけられている場合には、（ユーザー自身の認識はともかく）違反状況・対応方針を含めて基本的に大きな差異はないと認識していただければと思います。

私からの以前の返答が誤解を生む表現となっておりましたら、たいへん申し訳ございません。
現状で制限がかかっているアカウントにつきましては今しばらく様子を見ていただくようお願いいたします。
また、個別の対応については基本的に受け付けない方針であること、恐縮ですが今一度ご了承ください。

**Comment by tottoko8686** [comment]
ご回答ありがとうございます。問題のある人物が迷惑行為を行ったのが元凶で厳しい対応になったのは仕方がありません。

処遇について確認したかったのはそのような悪質な作問者で手動で制限された人物と機械的に制限されている人物がいて、
手動で制限された側が時限的に解除されるのはおかしな話だし、解除されるにしても機械的に制限された側と
手動で制限された側の制限されるまでの時間が一緒というのは変だと思ったのでそれを確認したかったのです。

ご回答のこの処遇は同じ、基本的に大きな差異はないというのはそのままの意味で
どんな状況でどんな理由で制限になっているとしても同じような対応、特別扱いはしませんよということでしょうか？
それとも極端な例で例えますが放火と故意ではない事故は重さは違えど罪は罪。
刑期（制限解除までの期間）から何もかも同じの扱いだという意味も含めてでしょうか？

お手数おかけしますがご回答よろしくお願いします。

**Comment by tottoko8686** [comment]
ご回答、ご対応ありがとうございました。

**Comment by tottoko8686** [comment]
こちらでの対応では時間経過により解除されるのをいましばらくお待ちいただければと思います。や今しばらく変化がないか様子を見ていただくようお願いいたします。問題投稿制限が解除されたのちに指摘問題の修正を行う際は、「指摘マークを消す」のチェックを入れて投稿するようご注意ください。など書かれていましたが#1087では解除の可能性が完全否定されています。どういうことでしょうか？

**Comment by toripii** [comment]
ご返信遅くなり申し訳ございません。
上記について確認いたしました。
認識どおりで間違いございません。一度指摘多数による制限を受けたユーザーにおかれましては、現時点で作問権限が復活することはありません。

本件は状況変化なしとしてクローズいたします。今後の方針転換等予定しておりませんが、要望等ございましたら別件でチケットを作成していた抱きますようお願いいたします。
以上恐縮ですが、ご承知おきください。
