### ISSUE TITLE
テーマモードの権限の申請の可否が降りない

### ISSUE THREAD

**Issue by hideyoshikun** [nodchip/QMAClone#1095]
現在テーマモードの権限の申請を行っていますが、1週間経過しても申請中のままの状態です。
申請の可否を行っていただくことは可能でしょうか。

**Comment by toripii** [comment]
対応が大変遅くなり申し訳ございません。
管理人様に問い合わせを行い、申請許可をいたしましたので、ご確認をお願いいたします。
