### ISSUE TITLE
消えたアカウントの復旧願い

### ISSUE THREAD

**Issue by Sugano-Yuta** [nodchip/QMAClone#1096]
初めまして
突然のメッセージ失礼します。

久しぶりにQMACloneをプレイしようとしたところ、アカウントがなぜか消えており復旧依頼をしに来ました。
ユーザーコードを入力すればいいのですが、ユーザーコードを忘れてしまい、プレイヤー名しか覚えていません。

ユーザー名は「JAJ6A」です。

よろしくお願いします。

**Comment by nodchip** [comment]
お問い合わせありがとうございます。
アカウントの復旧は Twitter の DM で対応しております。
そちらのほうにメッセージをいただいてもよろしいでしょうか？
よろしくお願いいたします。

**Comment by Sugano-Yuta** [comment]
わかりました
@sosfff931からDMを送りました

**Comment by nodchip** [comment]
対応完了いたしました。
