### ISSUE TITLE
アイコン変更時にエラーが発生する

### ISSUE THREAD

**Issue by tottoko8686** [nodchip/QMAClone#1097]
ご無沙汰しております。本日アイコンを変更しようとしたところ「アップロード中にエラーが発生しました。
頻繁に発生する場合は管理人にお知らせください」と表示されました。ちなみに3月30日にプレイした時には
問題ありませんでした。バグ？の修復よろしくお願いします。

**Comment by toripii** [comment]
返信が遅くなり申し訳ございません。
本件管理人様より対応完了の連絡をいただきましたので、再度エラーが発生するかご確認いただけますでしょうか。
よろしくお願いいたします。

**Comment by tottoko8686** [comment]
先程、確認したところ無事変更できました。迅速な対応に感謝いたします。ありがとうございました。

**Comment by tottoko8686** [comment]
こんばんは。本日アイコンの変更を行おうとしたところ以前とと同じ状態になりました。
ちなみに前回8月17日には変更出来ていました。バグ？の修復よろしくお願いします。

**Comment by nodchip** [comment]
ご報告いただきありがとうございます。今しがた設定を修正いたしました。明日の朝には適用されていると思います。

**Comment by tottoko8686** [comment]
先程確認いたしましたが、適用されていないようです。お多数かけますがまた設定の確認、修復作業よろしくお願いします。

**Comment by nodchip** [comment]
失礼いたしました。本日のサーバーメンテナンスで、変更が元に戻ってしまっていたようです。今しがた、再度設定を修正いたしました。明日の朝に適用されると思います。

**Comment by tottoko8686** [comment]
先程、確認したところ無事変更できました。迅速な対応感謝いたします。ありがとうございました。
